[project]
name = "test-framework"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1.5",
    "pyyaml>=6.0.3",
    "tabulate>=0.9.0",
    "wcwidth==0.2.14",
]
